repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-added-large-files
      - id: check-toml
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: local
    hooks:
      - id: pydoclint
        name: pydoclint
        entry: pydoclint
        language: python
        types: [python]
        args: ["--generate-baseline=True"]
        additional_dependencies: ["pydoclint"]
      - id: ruff
        name: ruff
        entry: ruff check
        args: [--fix]
        language: python
        types_or: [python, pyi]
      - id: ruff-format
        name: ruff-format
        entry: ruff format
        language: python
        types_or: [python, pyi]
