#!/usr/bin/env bash
#
# Cleans up all artifacts generated by the test suite.
# This script should be run from the root of the repository.

echo "Cleaning up test artifacts..."

# Remove the main data output directory
rm -rf data/

# Remove coverage report files and database
rm -rf htmlcov/
rm -f .coverage

# Remove specific log files and default outputs
rm -f error.log
rm -f out.csv

# Remove all fail and bis files from any directory
# The find command is robust and will search recursively.
find . -name "*.fail.csv" -type f -delete
find . -name "*_failed.csv" -type f -delete

echo "Cleanup complete."
